blank_issues_enabled: true
contact_links:
  - name: ðŸ”— Have a question on how to use ROS?
    url: https://robotics.stackexchange.com/
    about: We use Robotics Stack Exchange for general project questions.
  - name: ðŸ”— Looking for documentation on active ROS distros?
    url: https://docs.ros.org/
    about: The ROS documentation is available at docs.ros.org
  - name: ðŸ”— Want to discuss a ROS feature or get the latest ROS news?
    url: https://discourse.ros.org/
    about: ROS Discourse is our community discussion forum.
  - name: ðŸ”— Do you need real time support from other ROS users?
    url: https://openrobotics.zulipchat.com/
    about: Visit our community Zulip server. ROS questions belong in "ROS General" channel.
  - name: ðŸ”— Want to check ROS infrastructure status?
    url: https://status.openrobotics.org/
    about: Status page for ROS websites and resources.
